@SecurityAssessmentAPI_HostAddress = http://localhost:5052

GET {{SecurityAssessmentAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{SecurityAssessmentAPI_HostAddress}}/api/ssl/check
Content-Type: application/json

{
  "domain": "google.com"
}

###

GET {{SecurityAssessmentAPI_HostAddress}}/api/ssl/check/google.com
Accept: application/json

###
